import type { PromptsData, BrandNames } from "./types"

export const brandNames: BrandNames = {
  DO: "DealerOn",
  DI: "Dealer Inspire",
  CD: "CDK Global",
  AT: "AutoTrader",
  CC: "Cars.com",
}

export const mockRealistic: PromptsData = {
  items: [
    {
      id: 1,
      prompt: "best car dealer website platforms for lead generation",
      visibilityScore: 91,
      sentiment: 89,
      volume: 18500,
      difficulty: 52,
      brands: ["DO", "DI", "CD"],
      isAnalyzing: false,
    },
    {
      id: 2,
      prompt: "top automotive SEO companies for dealerships",
      visibilityScore: 88,
      sentiment: 92,
      volume: 22400,
      difficulty: 68,
      brands: ["DO", "DI"],
      isAnalyzing: false,
    },
    {
      id: 3,
      prompt: "how to increase car dealership website conversions",
      visibilityScore: 85,
      sentiment: 87,
      volume: 31200,
      difficulty: 44,
      brands: ["DO", "CD"],
      isAnalyzing: false,
    },
    {
      id: 4,
      prompt: "best digital advertising solutions for auto dealers",
      visibilityScore: 82,
      sentiment: 91,
      volume: 14800,
      difficulty: 61,
      brands: ["DO", "DI", "AT"],
      isAnalyzing: false,
    },
    {
      id: 5,
      prompt: "dealer website providers comparison 2025",
      visibilityScore: 79,
      sentiment: 84,
      volume: 9600,
      difficulty: 75,
      brands: ["DO", "DI", "CD"],
      isAnalyzing: false,
    },
    {
      id: 6,
      prompt: "automotive digital retailing tools for car dealerships",
      visibilityScore: 76,
      sentiment: 86,
      volume: 27300,
      difficulty: 38,
      brands: ["DO", "CD"],
      isAnalyzing: false,
    },
    {
      id: 7,
      prompt: "how to optimize dealership inventory pages for search",
      visibilityScore: 84,
      sentiment: 88,
      volume: 12700,
      difficulty: 55,
      brands: ["DO", "DI"],
      isAnalyzing: false,
    },
    {
      id: 8,
      prompt: "best SRP and VDP design for car dealer websites",
      visibilityScore: 73,
      sentiment: 82,
      volume: 8400,
      difficulty: 47,
      brands: ["DO"],
      isAnalyzing: false,
    },
    {
      id: 9,
      prompt: "fixed ops marketing strategies for service departments",
      visibilityScore: 71,
      sentiment: 79,
      volume: 15900,
      difficulty: 33,
      brands: ["DO", "DI"],
      isAnalyzing: false,
    },
    {
      id: 10,
      prompt: "OEM certified website providers for car dealerships",
      visibilityScore: 87,
      sentiment: 93,
      volume: 11200,
      difficulty: 82,
      brands: ["DO", "DI", "CD"],
      isAnalyzing: false,
    },
    {
      id: 11,
      prompt: "how to get more leads from dealership Google Ads",
      visibilityScore: 68,
      sentiment: 81,
      volume: 35600,
      difficulty: 59,
      brands: ["DO", "AT"],
      isAnalyzing: false,
    },
    {
      id: 12,
      prompt: "car dealer CRM integration with website platform",
      visibilityScore: 74,
      sentiment: 85,
      volume: 19800,
      difficulty: 71,
      brands: ["DO", "CD"],
      isAnalyzing: false,
    },
    {
      id: 13,
      prompt: "best practices for dealership reputation management online",
      visibilityScore: 66,
      sentiment: 77,
      volume: 24100,
      difficulty: 42,
      brands: ["DO", "CC"],
      isAnalyzing: false,
    },
    {
      id: 14,
      prompt: "automotive PPC management for multi-rooftop dealers",
      visibilityScore: 78,
      sentiment: 90,
      volume: 7800,
      difficulty: 66,
      brands: ["DO", "DI"],
      isAnalyzing: false,
    },
    {
      id: 15,
      prompt: "dealership website ADA compliance requirements",
      visibilityScore: 81,
      sentiment: 83,
      volume: 13400,
      difficulty: 29,
      brands: ["DO", "CD", "DI"],
      isAnalyzing: false,
    },
  ],
}

export const mockEmpty: PromptsData = {
  items: [],
}

export const mockStress: PromptsData = {
  items: Array.from({ length: 50 }, (_, i) => ({
    id: i + 1,
    prompt: i % 5 === 0
      ? "extremely long prompt text that tests how the UI handles very long strings in the table cell without breaking the layout or causing horizontal scroll issues in the dashboard"
      : `automotive dealership prompt variation ${i + 1} for SEO and content optimization`,
    visibilityScore: i % 7 === 0 ? null : Math.floor(Math.random() * 100),
    sentiment: i % 9 === 0 ? null : Math.floor(Math.random() * 100),
    volume: i % 6 === 0 ? null : Math.floor(Math.random() * 50000),
    difficulty: i % 8 === 0 ? null : Math.floor(Math.random() * 100),
    brands: i % 4 === 0 ? [] : ["DO", "DI", "CD", "AT", "CC"].slice(0, (i % 5) + 1),
    isAnalyzing: i % 10 === 0,
  })),
}

export const mockError = {
  title: "Failed to load prompts",
  message: "We couldn't retrieve your prompt data. Please check your connection and try again.",
  code: "ERR_PROMPTS_FETCH",
}
