import type { ContentGapsData } from "./types"

export const mockRealistic: ContentGapsData = {
  stats: {
    coveragePercent: 57,
    changePercent: 5.8,
    promptsCovered: 8,
    totalPrompts: 14,
    fullCoverage: 2,
    partialCoverage: 4,
    noCoverage: 2,
  },
  recommendations: [
    {
      rank: 1,
      title: "EV Inventory Page Optimization",
      description: "Create dedicated landing pages for electric vehicle inventory with charging info",
      prompts: 5,
    },
    {
      rank: 2,
      title: "Service Department Online Scheduling",
      description: "Publish content around online service booking and maintenance packages",
      prompts: 3,
    },
    {
      rank: 3,
      title: "Trade-In Value Tools Comparison",
      description: "Create comparison guides for trade-in valuation tools",
      prompts: 8,
    },
  ],
  items: [
    {
      id: 1,
      prompt: "EV Inventory Page Optimization",
      coveragePercent: 0,
      citations: 3,
      queries: 5,
      changePercent: 12,
      lastAnalyzed: "9 Feb",
    },
    {
      id: 2,
      prompt: "Service Department Online Scheduling",
      coveragePercent: 35,
      citations: 2,
      queries: 3,
      changePercent: 9,
      lastAnalyzed: "8 Feb",
    },
    {
      id: 3,
      prompt: "Trade-In Value Tools Comparison",
      coveragePercent: 85,
      citations: 3,
      queries: 4,
      changePercent: 4,
      lastAnalyzed: "11 Feb",
    },
    {
      id: 4,
      prompt: "Online Car Buying Process",
      coveragePercent: 12,
      citations: 5,
      queries: 12,
      changePercent: -3,
      lastAnalyzed: "10 Feb",
    },
    {
      id: 5,
      prompt: "Dealership Website ADA Compliance",
      coveragePercent: 92,
      citations: 4,
      queries: 4,
      changePercent: 1,
      lastAnalyzed: "7 Feb",
    },
    {
      id: 6,
      prompt: "Auto Loan Pre-Qualification Online",
      coveragePercent: 8,
      citations: 2,
      queries: 9,
      changePercent: 15,
      lastAnalyzed: "9 Feb",
    },
    {
      id: 7,
      prompt: "Used Car Certification Programs",
      coveragePercent: 48,
      citations: 3,
      queries: 7,
      changePercent: 6,
      lastAnalyzed: "11 Feb",
    },
    {
      id: 8,
      prompt: "Dealership Google Business Profile Optimization",
      coveragePercent: 78,
      citations: 2,
      queries: 3,
      changePercent: 2,
      lastAnalyzed: "8 Feb",
    },
    {
      id: 9,
      prompt: "Vehicle Delivery Experience",
      coveragePercent: 5,
      citations: 1,
      queries: 4,
      changePercent: -1,
      lastAnalyzed: "6 Feb",
    },
    {
      id: 10,
      prompt: "Fleet Sales Programs",
      coveragePercent: 22,
      citations: 2,
      queries: 3,
      changePercent: 7,
      lastAnalyzed: "10 Feb",
    },
    {
      id: 11,
      prompt: "Dealer Website Mobile Experience",
      coveragePercent: 55,
      citations: 4,
      queries: 6,
      changePercent: 3,
      lastAnalyzed: "9 Feb",
    },
    {
      id: 12,
      prompt: "Recall Information and Service",
      coveragePercent: 0,
      citations: 3,
      queries: 5,
      changePercent: 18,
      lastAnalyzed: "11 Feb",
    },
  ],
}

export const mockEmpty: ContentGapsData = {
  stats: {
    coveragePercent: 100,
    changePercent: 0,
    promptsCovered: 0,
    totalPrompts: 0,
    fullCoverage: 0,
    partialCoverage: 0,
    noCoverage: 0,
  },
  recommendations: [],
  items: [],
}

export const mockStress: ContentGapsData = {
  stats: {
    coveragePercent: 12,
    changePercent: -2.4,
    promptsCovered: 6,
    totalPrompts: 80,
    fullCoverage: 2,
    partialCoverage: 4,
    noCoverage: 74,
  },
  recommendations: [
    { rank: 1, title: "Content Gap Topic 1 — Long recommendation to test truncation behavior", description: "Detailed description of what needs to be done for this particular gap", prompts: 12 },
    { rank: 2, title: "Content Gap Topic 2 — Another long recommendation title", description: "More details on action items and next steps", prompts: 9 },
    { rank: 3, title: "Content Gap Topic 3 — Yet another recommendation", description: "Expand coverage on this important topic area", prompts: 7 },
  ],
  items: Array.from({ length: 50 }, (_, i) => ({
    id: i + 1,
    prompt: `Content Gap Topic ${i + 1} — Long topic name to test text truncation and table layout behavior`,
    coveragePercent: Math.floor(Math.random() * 100),
    citations: Math.floor(Math.random() * 10) + 1,
    queries: Math.floor(Math.random() * 15) + 1,
    changePercent: Math.floor(Math.random() * 30) - 5,
    lastAnalyzed: `${Math.floor(Math.random() * 28) + 1} Feb`,
  })),
}

export const mockError = {
  title: "Failed to load content gaps",
  message: "We couldn't retrieve the content gap analysis. Please try again.",
  code: "CONTENT_GAPS_FETCH_ERROR",
}
