import type { ContentGapsData } from "./types"

export const mockRealistic: ContentGapsData = {
  stats: {
    coveragePercent: 37,
    totalTopics: 24,
    coveredTopics: 5,
    partiallyCovered: 4,
    notCovered: 15,
  },
  items: [
    {
      id: 1,
      topic: "EV Inventory Page Optimization",
      category: "Electric Vehicles",
      coverageStatus: "not-covered",
      promptCount: 8,
      competitorsCovering: 4,
      totalCompetitors: 5,
      priority: "high",
      recommendation: "Create dedicated landing pages for electric vehicle inventory with charging info and incentives",
    },
    {
      id: 2,
      topic: "Service Department Online Scheduling",
      category: "Fixed Ops",
      coverageStatus: "not-covered",
      promptCount: 6,
      competitorsCovering: 3,
      totalCompetitors: 5,
      priority: "high",
      recommendation: "Publish content around online service booking, recall notifications, and maintenance packages",
    },
    {
      id: 3,
      topic: "Trade-In Value Tools Comparison",
      category: "Trade-In",
      coverageStatus: "partially-covered",
      promptCount: 5,
      competitorsCovering: 3,
      totalCompetitors: 5,
      priority: "high",
      recommendation: "Create comparison guides for trade-in valuation tools and how dealers can offer instant appraisals",
    },
    {
      id: 4,
      topic: "Online Car Buying Process",
      category: "Digital Retailing",
      coverageStatus: "not-covered",
      promptCount: 12,
      competitorsCovering: 5,
      totalCompetitors: 5,
      priority: "high",
      recommendation: "Build end-to-end online purchase flow documentation and marketing content",
    },
    {
      id: 5,
      topic: "Dealership Website ADA Compliance",
      category: "Compliance",
      coverageStatus: "covered",
      promptCount: 4,
      competitorsCovering: 2,
      totalCompetitors: 5,
      priority: "low",
      recommendation: "Maintain existing compliance content and keep updated with latest WCAG guidelines",
    },
    {
      id: 6,
      topic: "Auto Loan Pre-Qualification Online",
      category: "F&I",
      coverageStatus: "not-covered",
      promptCount: 9,
      competitorsCovering: 4,
      totalCompetitors: 5,
      priority: "high",
      recommendation: "Add finance pre-qualification tools and educational content about auto loan processes",
    },
    {
      id: 7,
      topic: "Used Car Certification Programs",
      category: "Inventory",
      coverageStatus: "partially-covered",
      promptCount: 7,
      competitorsCovering: 3,
      totalCompetitors: 5,
      priority: "medium",
      recommendation: "Expand CPO program pages with detailed inspection checklists and warranty comparison tables",
    },
    {
      id: 8,
      topic: "Dealership Google Business Profile Optimization",
      category: "Local SEO",
      coverageStatus: "covered",
      promptCount: 3,
      competitorsCovering: 2,
      totalCompetitors: 5,
      priority: "low",
      recommendation: "Continue updating GBP listings and encourage customer review generation",
    },
    {
      id: 9,
      topic: "Vehicle Delivery Experience",
      category: "Customer Experience",
      coverageStatus: "not-covered",
      promptCount: 4,
      competitorsCovering: 2,
      totalCompetitors: 5,
      priority: "medium",
      recommendation: "Create content showcasing your vehicle delivery process and at-home delivery options",
    },
    {
      id: 10,
      topic: "Fleet Sales Programs",
      category: "Commercial",
      coverageStatus: "not-covered",
      promptCount: 3,
      competitorsCovering: 1,
      totalCompetitors: 5,
      priority: "medium",
      recommendation: "Develop fleet sales landing pages with volume pricing and business account information",
    },
    {
      id: 11,
      topic: "Dealer Website Mobile Experience",
      category: "Technology",
      coverageStatus: "partially-covered",
      promptCount: 6,
      competitorsCovering: 4,
      totalCompetitors: 5,
      priority: "medium",
      recommendation: "Optimize mobile UX and create content highlighting mobile-first shopping features",
    },
    {
      id: 12,
      topic: "Recall Information and Service",
      category: "Fixed Ops",
      coverageStatus: "not-covered",
      promptCount: 5,
      competitorsCovering: 3,
      totalCompetitors: 5,
      priority: "high",
      recommendation: "Add recall lookup tools and educational content about recall service processes",
    },
  ],
}

export const mockEmpty: ContentGapsData = {
  stats: {
    coveragePercent: 100,
    totalTopics: 0,
    coveredTopics: 0,
    partiallyCovered: 0,
    notCovered: 0,
  },
  items: [],
}

export const mockStress: ContentGapsData = {
  stats: {
    coveragePercent: 12,
    totalTopics: 80,
    coveredTopics: 6,
    partiallyCovered: 4,
    notCovered: 70,
  },
  items: Array.from({ length: 50 }, (_, i) => ({
    id: i + 1,
    topic: `Content Gap Topic ${i + 1} — Long topic name to test text truncation and table layout behavior`,
    category: ["Electric Vehicles", "Fixed Ops", "Digital Retailing", "F&I", "Inventory", "Local SEO", "Compliance"][i % 7],
    coverageStatus: (["not-covered", "partially-covered", "covered"] as const)[i % 3],
    promptCount: Math.floor(Math.random() * 15) + 1,
    competitorsCovering: Math.floor(Math.random() * 5),
    totalCompetitors: 5,
    priority: (["high", "medium", "low"] as const)[i % 3],
    recommendation: `Recommendation for topic ${i + 1} with detailed action items and next steps for the content team.`,
  })),
}

export const mockError = {
  title: "Failed to load content gaps",
  message: "We couldn't retrieve the content gap analysis. Please try again.",
  code: "CONTENT_GAPS_FETCH_ERROR",
}
